# Arreglos y clases
## Matrices
Una matriz es un arreglo de $n * n$ elementos:

$$A = \begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{pmatrix}$$

In [3]:
A=[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
print(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [10]:
# Vamos a crear otra
B=[[21,34,40],[71,17,77],[73,81,28]]

In [18]:
A+B
2*A

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
A[0][0]

1

## Vectores y listas

In [19]:
L=A[0]
M=B[0]
L+M

[1, 2, 3, 21, 34, 40]

In [23]:
a=L[0]
b=M[0]
a+b

22

In [24]:
a==1

True

### Suma de "vectores"

In [25]:
len(L)==len(M)

True

In [28]:
suma=[L[0]+M[0],L[1]+M[1],L[2]+M[2]]
suma

[22, 36, 43]

In [ ]:
suma = [L[i]+M[i] for i in range(3)]

#### Creación de funciones globales

La funciòn para crear funciones es `def` que se cierra con un debug (`print` o `return`)

In [29]:
def Hola():
  print("Hola, me llamo Cèsar")

In [30]:
Hola()

Hola, me llamo Cèsar


In [36]:
def Saludar(s,n):
  print(f"Hola, me llamo {s} y tengo {n} años")

In [37]:
Saludar("Cesar",18)

Hola, me llamo Cesar y tengo 18 años


In [41]:
def Par(x):
  for x in range(x):
    if x%2==0:
      print(f"{x} es par")
    else:
      print(f"{x} es impar")

In [47]:
Par(10)

0 es par
1 es impar
2 es par
3 es impar
4 es par
5 es impar
6 es par
7 es impar
8 es par
9 es impar


In [49]:
def suma_vectorial(L,M):
  x = [L[i]+M[i] for i in range(len(L))]
  return x

In [50]:
L = [1,2,3]
M = [21,34,40]
suma_vectorial(L,M)

[22, 36, 43]

## Módulos o librerias


In [51]:
import math
from math import sqrt,pi

In [52]:
sqrt(68)

8.246211251235321

In [53]:
pi

3.141592653589793

# El módulo NumPy

La función `array`

In [54]:
import numpy as np

L_vector = np.array(L)
M_vector = np.array(M)

L_vector + M_vector

array([22, 36, 43])

In [59]:
C = [9,2,2,2,3,3,2,17,2]
A = [8,1,1,1,2,2,1,16,1]

C_matriz = np.array(C).reshape(3,3)
A_matriz = np.array(A).reshape(3,3)

print(C_matriz)
print(A_matriz)

[[ 9  2  2]
 [ 2  3  3]
 [ 2 17  2]]
[[ 8  1  1]
 [ 1  2  2]
 [ 1 16  1]]


In [57]:
C_matriz @ A_matriz

array([[76, 45, 15],
       [22, 56, 11],
       [35, 68, 38]])

In [58]:
A_matriz @ C_matriz

array([[76, 36, 21],
       [17, 42, 12],
       [43, 67, 52]])